# Generated by Django 4.2.2 on 2023-07-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='perfume_company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
