# Generated by Django 4.2.2 on 2023-08-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_like_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
