# Generated by Django 4.2.2 on 2023-08-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0006_post_edit_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('follow', 'follow'), ('unfollow', 'unfollow')], max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_media.account')),
            ],
        ),
    ]
