# Generated by Django 4.2.2 on 2023-08-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0007_follownotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='follownotification',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
