# Generated by Django 4.2.2 on 2023-08-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0008_follownotification_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='follownotification',
            name='username',
            field=models.CharField(default='username', max_length=200),
        ),
    ]
