# Generated by Django 4.2.2 on 2023-09-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0010_alter_follownotification_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follownotification',
            name='account',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='social_media.account'),
        ),
    ]
