# Generated by Django 4.2.2 on 2023-09-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0011_alter_follownotification_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follownotification',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='social_media.account', unique=True),
        ),
    ]
